version: '3.8'

services:
  timetracking:
    build: .
    container_name: timetracking-server
    ports:
      - "9999:9999"
      - "8080:8080"
    environment:
      - RELAY_PORT=9999
      - HTTP_PORT=8080
      - DB_PATH=/app/data/timetracking.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped